In [1]:
import os 

import os.path as osp
os.chdir(osp.dirname(os.getcwd()))


In [2]:
from data.model_util_scannet import ScannetDatasetConfig
import numpy as np 
import sys
from src.arkitscenes_dataset import ARKitSceneDataset

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


WARNING - 2022-10-17 22:38:28,612 - collision - No FCL -- collision checking will not work
WARNING - 2022-10-17 22:38:28,744 - svg_io - SVG path loading unavailable!


In [3]:




DATASET_CONFIG = ScannetDatasetConfig()

point_num = 50000

TRAIN_DATASET_WK = ARKitSceneDataset('train', num_points=point_num,
                                        augment=True,
                                        start_proportion=0.0,
                                        end_proportion=1.0,data_root='datasets/ARKitScenes')



TEST_DATASET_ARKIT = ARKitSceneDataset('valid', num_points=point_num,
                                            augment=False,
                                            start_proportion=0.0,
                                            end_proportion=1.0,)



Find 4364 in ARKitScene dataset!
Find 491 in ARKitScene dataset!


In [29]:
demo = TRAIN_DATASET_WK.__getitem__(0)
demo_test = TEST_DATASET_ARKIT.__getitem__(0)

FileNotFoundError: [Errno 2] No such file or directory: '/home/DISCOVER_summer2022/xusc/exp/butd_detr/src/data/annotations/000000.json'

In [24]:

print(list(demo.keys()))
#? vertex_normals 
#? heading_class_label 
#? heading_residual_label 
#? num_gt_boxes 


['scan_name', 'point_clouds', 'vertex_normals', 'ema_point_clouds', 'flip_x_axis', 'flip_y_axis', 'rot_mat', 'scale', 'center_label', 'heading_class_label', 'heading_residual_label', 'size_label', 'num_gt_boxes']


(50000, 3)

In [19]:
demo['center_label'][0,:], demo['center_label'].shape

(array([ 1.5945847, -1.5421475, -1.1684961], dtype=float32), (64, 3))

In [21]:
demo['heading_class_label']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
demo['heading_residual_label']



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [28]:
demo['num_gt_boxes'].shape

(256,)